version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: sass
    versions:
    - 1.32.11
  - dependency-name: core-js
    versions:
    - 3.10.0
    - 3.10.2
    - 3.8.3
    - 3.9.0
    - 3.9.1
  - dependency-name: socket.io
    versions:
    - 3.1.1
    - 3.1.2
    - 4.0.0
  - dependency-name: "@ckeditor/ckeditor5-build-inline"
    versions:
    - 25.0.0
    - 26.0.0
  - dependency-name: "@stripe/stripe-js"
    versions:
    - 1.12.1
    - 1.13.0
    - 1.13.1
  - dependency-name: v-calendar
    versions:
    - 2.2.3
    - 2.2.4
  - dependency-name: d3-dag
    versions:
    - 0.6.2
  - dependency-name: vue-cal
    versions:
    - 3.10.0
  - dependency-name: nuxt
    versions:
    - 2.14.12
